export type QuizQuestion = {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
};

export type Flashcard = {
  front: string;
  back: string;
};

export type CourseLesson = {
  id: string;
  module: number;
  lesson: number;
  title: string;
  duration: string;
  youtubeUrl?: string;
  description: string;
  objectives: string[];
  keyPoints: string[];
  actionStep: string;
  quiz: QuizQuestion[];
  flashcards: Flashcard[];
};

export const businessCourse = {
  title: "Business Management & Leadership",
  instructor: "Purity of Hearts + curated business educators",
  description:
    "A practical business-management program covering finance, strategy, marketing, operations, leadership, administration, customer service, customer discovery, and growth.",
  modules: [
    {
      number: 1,
      title: "Business Foundations",
      description: "Understand the financial and strategic foundations of a business.",
    },
    {
      number: 2,
      title: "Marketing & Operations",
      description: "Build repeatable systems for promotion, delivery, quality, and customers.",
    },
    {
      number: 3,
      title: "People, Research & Administration",
      description: "Manage people, research ideas, and organize essential business processes.",
    },
    {
      number: 4,
      title: "Accounting, Economics & Planning",
      description: "Understand accounting, economics, demand, supply, and budgeting.",
    },
    {
      number: 5,
      title: "Growth & Customer Acquisition",
      description: "Attract customers, grow revenue, and compete effectively.",
    },
    {
      number: 6,
      title: "Launch & Leadership",
      description: "Launch products and become a stronger business leader.",
    },
    {
      number: 7,
      title: "Customer Discovery & Validation",
      description:
        "Choose stronger ideas, interview real customers, and validate demand before overbuilding.",
    },
    {
      number: 8,
      title: "Modern Marketing Systems",
      description:
        "Turn digital marketing, social media, and useful content into a focused growth system.",
    },
    {
      number: 9,
      title: "Purposeful Leadership",
      description:
        "Communicate a clear purpose, lead with trust, and give feedback that helps people grow.",
    },
  ],
};

const placeholderQuiz = (title: string): QuizQuestion[] => [
  {
    question: `What is the primary purpose of the lesson "${title}"?`,
    options: [
      "To provide a practical business-management framework",
      "To eliminate the need for planning",
      "To guarantee immediate profits",
      "To replace all professional advice",
    ],
    correctAnswer: 0,
    explanation:
      "The lesson is designed to provide a practical framework that can be applied to business decisions.",
  },
];

const placeholderFlashcards = (title: string): Flashcard[] => [
  {
    front: title,
    back: "Review the lesson and write the three most important principles in your own words.",
  },
];

export const businessLessons: CourseLesson[] = [
  {
    id: "business-finance",
    module: 1,
    lesson: 1,
    title: "Business Finance in Business Management",
    duration: "2:51",
    youtubeUrl: "https://www.youtube.com/embed/T3l51Psce3c",
    description:
      "Learn why financial management is central to starting, operating, and growing a sustainable business.",
    objectives: [
      "Understand the purpose of business finance.",
      "Separate revenue, profit, cash flow, expenses, assets, and liabilities.",
      "Recognize why financial records influence business decisions.",
      "Create a basic financial review routine for a business.",
    ],
    keyPoints: [
      "Revenue is the money generated before expenses are deducted.",
      "Profit is what remains after applicable expenses are subtracted.",
      "Cash flow measures money entering and leaving the business.",
      "A profitable business can still experience cash-flow problems.",
      "Budgets create spending limits and support better decisions.",
      "Financial records help owners measure performance and prepare for growth.",
    ],
    actionStep:
      "Create a one-page financial snapshot showing estimated monthly revenue, fixed expenses, variable expenses, cash available, debt, and expected profit.",
    quiz: [
      {
        question: "What does business revenue represent?",
        options: [
          "Money earned before expenses",
          "Money remaining after all expenses",
          "Only the cash stored in a bank account",
          "The total value of business debt",
        ],
        correctAnswer: 0,
        explanation:
          "Revenue is the income generated by the business before expenses are deducted.",
      },
      {
        question: "What is profit?",
        options: [
          "Revenue plus expenses",
          "Money remaining after expenses",
          "The owner's personal salary only",
          "All money received from investors",
        ],
        correctAnswer: 1,
        explanation:
          "Profit is generally the amount remaining after relevant business expenses are deducted from revenue.",
      },
      {
        question: "Why is cash flow important?",
        options: [
          "It tracks money moving into and out of the business",
          "It guarantees customers",
          "It removes all business risk",
          "It replaces a business budget",
        ],
        correctAnswer: 0,
        explanation:
          "Cash flow helps a business determine whether it has enough available cash to meet obligations.",
      },
      {
        question: "Which item is normally a fixed expense?",
        options: [
          "Monthly office rent",
          "Packaging that changes with order volume",
          "Sales commission",
          "Transaction fees tied to sales",
        ],
        correctAnswer: 0,
        explanation:
          "Office rent is normally consistent each month, making it a fixed expense.",
      },
      {
        question: "What is the strongest financial habit for a new owner?",
        options: [
          "Reviewing income, expenses, cash flow, and profit consistently",
          "Only reviewing finances once a year",
          "Mixing personal and business spending",
          "Ignoring small recurring expenses",
        ],
        correctAnswer: 0,
        explanation:
          "Consistent financial reviews help owners identify problems and make informed decisions.",
      },
    ],
    flashcards: [
      {
        front: "Revenue",
        back: "The total income generated by a business before expenses are deducted.",
      },
      {
        front: "Profit",
        back: "The amount remaining after applicable business expenses are subtracted from revenue.",
      },
      {
        front: "Cash Flow",
        back: "The movement of cash into and out of a business.",
      },
      {
        front: "Fixed Expense",
        back: "A recurring cost that generally remains stable, such as rent or a base software subscription.",
      },
      {
        front: "Variable Expense",
        back: "A cost that changes with activity or sales volume, such as packaging or transaction fees.",
      },
      {
        front: "Asset",
        back: "A resource owned or controlled by the business that has economic value.",
      },
      {
        front: "Liability",
        back: "A financial obligation or amount the business owes.",
      },
      {
        front: "Budget",
        back: "A financial plan showing expected income, expenses, and allocation of money.",
      },
    ],
  },

  {
    id: "management-strategy",
    module: 1,
    lesson: 2,
    title: "6 Steps to Write Business Management Strategy for Your Own Business",
    duration: "2:32",
    youtubeUrl: "https://www.youtube.com/embed/gGE4GUv1-F0",
    description: "Create a clear strategy that connects goals, resources, execution, and measurement.",
    objectives: ["Define a business direction.", "Set measurable priorities.", "Create an execution plan."],
    keyPoints: ["Define the vision.", "Study the market.", "Set goals.", "Assign resources.", "Execute.", "Review results."],
    actionStep: "Write a one-page management strategy for your business.",
    quiz: placeholderQuiz("Business Management Strategy"),
    flashcards: placeholderFlashcards("Business Management Strategy"),
  },
  {
    id: "marketing-methods",
    module: 2,
    lesson: 3,
    title: "Top 40 Business Marketing Methods",
    duration: "2:56",
    youtubeUrl: "https://www.youtube.com/embed/uaTTzNgRt-o",
    description: "Explore marketing channels that can support awareness, leads, sales, and retention.",
    objectives: ["Identify marketing channels.", "Match channels to customers.", "Prioritize measurable methods."],
    keyPoints: ["Know the audience.", "Use multiple channels.", "Measure acquisition.", "Improve what performs."],
    actionStep: "Select five marketing methods to test over the next 30 days.",
    quiz: placeholderQuiz("Business Marketing Methods"),
    flashcards: placeholderFlashcards("Business Marketing Methods"),
  },
  {
    id: "business-operations",
    module: 2,
    lesson: 4,
    title: "7 Steps of Business Operations",
    duration: "2:30",
    youtubeUrl: "https://www.youtube.com/embed/n5QbXvDAZN8",
    description: "Design the operational process that moves work from customer demand to delivery.",
    objectives: ["Map an operating workflow.", "Assign responsibilities.", "Measure efficiency."],
    keyPoints: ["Inputs.", "Processes.", "People.", "Quality.", "Delivery.", "Measurement.", "Improvement."],
    actionStep: "Map one customer order from purchase to final delivery.",
    quiz: placeholderQuiz("Business Operations"),
    flashcards: placeholderFlashcards("Business Operations"),
  },
  {
    id: "human-resource-management",
    module: 3,
    lesson: 5,
    title: "Human Resource Management Explained",
    duration: "2:37",
    youtubeUrl: "https://www.youtube.com/embed/PhkcstGNWtc",
    description: "Understand hiring, onboarding, performance, compliance, and employee development.",
    objectives: ["Understand HR functions.", "Plan hiring.", "Create employee standards."],
    keyPoints: ["Recruiting.", "Onboarding.", "Training.", "Performance.", "Culture.", "Documentation."],
    actionStep: "Draft a basic role description and onboarding checklist.",
    quiz: placeholderQuiz("Human Resource Management"),
    flashcards: placeholderFlashcards("Human Resource Management"),
  },
  {
    id: "business-research",
    module: 3,
    lesson: 6,
    title: "3 Business Research Methods for New Business Ideas",
    duration: "2:16",
    youtubeUrl: "https://www.youtube.com/embed/jctM1Rcaeo4",
    description: "Research customers, competitors, and market demand before investing heavily.",
    objectives: ["Conduct customer research.", "Review competitors.", "Test demand."],
    keyPoints: ["Primary research.", "Secondary research.", "Market experiments."],
    actionStep: "Interview five potential customers about one specific problem.",
    quiz: placeholderQuiz("Business Research"),
    flashcards: placeholderFlashcards("Business Research"),
  },
  {
    id: "management-skills",
    module: 3,
    lesson: 7,
    title: "Start a Business With 50 Business Management Skills",
    duration: "3:11",
    youtubeUrl: "https://www.youtube.com/embed/c1Z-rATTTxE",
    description: "Review the core skills entrepreneurs need to plan, lead, sell, and operate.",
    objectives: ["Identify skill gaps.", "Prioritize development.", "Build a learning plan."],
    keyPoints: ["Leadership.", "Communication.", "Finance.", "Sales.", "Operations.", "Decision-making."],
    actionStep: "Rate yourself from one to five in ten essential management skills.",
    quiz: placeholderQuiz("Business Management Skills"),
    flashcards: placeholderFlashcards("Business Management Skills"),
  },
  {
    id: "quality-management",
    module: 2,
    lesson: 8,
    title: "Grow Business With Better Quality Management",
    duration: "2:22",
    youtubeUrl: "https://www.youtube.com/embed/HMSfAk_igCI",
    description: "Use quality standards and feedback systems to improve delivery and retention.",
    objectives: ["Define quality.", "Measure errors.", "Build improvement routines."],
    keyPoints: ["Standards.", "Inspection.", "Feedback.", "Correction.", "Continuous improvement."],
    actionStep: "Create a five-point quality checklist for your main product or service.",
    quiz: placeholderQuiz("Quality Management"),
    flashcards: placeholderFlashcards("Quality Management"),
  },
  {
    id: "business-documents",
    module: 3,
    lesson: 9,
    title: "40 Business Documents You Need When Starting a Business",
    duration: "3:15",
    youtubeUrl: "https://www.youtube.com/embed/72rTAyxd974",
    description: "Organize the operational, financial, legal, and sales documents used by a business.",
    objectives: ["Identify key documents.", "Create document categories.", "Build a secure filing process."],
    keyPoints: ["Formation.", "Finance.", "Contracts.", "Sales.", "HR.", "Operations."],
    actionStep: "Build a document checklist and secure folder structure.",
    quiz: placeholderQuiz("Business Documents"),
    flashcards: placeholderFlashcards("Business Documents"),
  },
  {
    id: "self-management",
    module: 1,
    lesson: 10,
    title: "Start a Business With Self Management",
    duration: "2:03",
    youtubeUrl: "https://www.youtube.com/embed/aQedlJk4zcA",
    description: "Improve discipline, time management, planning, and personal accountability.",
    objectives: ["Manage priorities.", "Create routines.", "Reduce founder bottlenecks."],
    keyPoints: ["Time blocking.", "Priorities.", "Delegation.", "Review.", "Accountability."],
    actionStep: "Design your ideal weekly founder schedule.",
    quiz: placeholderQuiz("Self Management"),
    flashcards: placeholderFlashcards("Self Management"),
  },
  {
    id: "customer-service",
    module: 5,
    lesson: 11,
    title: "How to Provide Great Customer Service",
    duration: "2:19",
    youtubeUrl: "https://www.youtube.com/embed/EiIlIHDqt-Q",
    description: "Build a service process that earns trust, retention, referrals, and repeat business.",
    objectives: ["Set service standards.", "Handle complaints.", "Improve retention."],
    keyPoints: ["Responsiveness.", "Empathy.", "Clarity.", "Resolution.", "Follow-up."],
    actionStep: "Write a customer-service response standard for your team.",
    quiz: placeholderQuiz("Customer Service"),
    flashcards: placeholderFlashcards("Customer Service"),
  },
  {
    id: "business-administration",
    module: 3,
    lesson: 12,
    title: "Business Administration in 2 Minutes",
    duration: "1:45",
    youtubeUrl: "https://www.youtube.com/embed/6mkoGSqTqFI",
    description: "Understand the coordination of records, schedules, communication, policies, and workflows.",
    objectives: ["Define administration.", "Organize recurring tasks.", "Improve internal control."],
    keyPoints: ["Records.", "Communication.", "Scheduling.", "Policies.", "Coordination."],
    actionStep: "List every recurring administrative task in your business.",
    quiz: placeholderQuiz("Business Administration"),
    flashcards: placeholderFlashcards("Business Administration"),
  },
  {
    id: "business-accounting",
    module: 4,
    lesson: 13,
    title: "How to Learn Business Accounting",
    duration: "1:44",
    youtubeUrl: "https://www.youtube.com/embed/0a4tXP7m_N0",
    description: "Learn the role of records, statements, categorization, and financial reporting.",
    objectives: ["Understand bookkeeping.", "Recognize financial statements.", "Track transactions."],
    keyPoints: ["Income statement.", "Balance sheet.", "Cash flow statement.", "Reconciliation."],
    actionStep: "Create categories for the income and expenses in your business.",
    quiz: placeholderQuiz("Business Accounting"),
    flashcards: placeholderFlashcards("Business Accounting"),
  },
  {
    id: "management-mistakes",
    module: 1,
    lesson: 14,
    title: "20 Business Management Mistakes to Avoid",
    duration: "1:55",
    youtubeUrl: "https://www.youtube.com/embed/dABkukhG08A",
    description: "Recognize common planning, finance, hiring, marketing, and execution mistakes.",
    objectives: ["Identify common risks.", "Audit current practices.", "Create prevention controls."],
    keyPoints: ["Poor planning.", "Weak finances.", "No customer validation.", "Bad hiring.", "No measurement."],
    actionStep: "Identify three current risks and assign one preventive action to each.",
    quiz: placeholderQuiz("Business Management Mistakes"),
    flashcards: placeholderFlashcards("Business Management Mistakes"),
  },
  {
    id: "demand-supply",
    module: 4,
    lesson: 15,
    title: "Understanding Demand and Supply",
    duration: "1:50",
    youtubeUrl: "https://www.youtube.com/embed/ufhcZyMPgQk",
    description: "Understand how customer demand and market supply influence pricing and opportunity.",
    objectives: ["Define demand.", "Define supply.", "Connect both concepts to pricing."],
    keyPoints: ["Demand.", "Supply.", "Price.", "Scarcity.", "Competition."],
    actionStep: "Describe the demand and supply conditions for your offer.",
    quiz: placeholderQuiz("Demand and Supply"),
    flashcards: placeholderFlashcards("Demand and Supply"),
  },
  {
    id: "business-economics",
    module: 4,
    lesson: 16,
    title: "Basics of Business Economics",
    duration: "1:56",
    youtubeUrl: "https://www.youtube.com/embed/e5L3XgLPtZQ",
    description: "Apply basic economic thinking to costs, pricing, competition, and decision-making.",
    objectives: ["Understand opportunity cost.", "Analyze market forces.", "Improve allocation decisions."],
    keyPoints: ["Scarcity.", "Opportunity cost.", "Competition.", "Incentives.", "Productivity."],
    actionStep: "Identify the opportunity cost of your largest current business decision.",
    quiz: placeholderQuiz("Business Economics"),
    flashcards: placeholderFlashcards("Business Economics"),
  },
  {
    id: "budget-plan",
    module: 4,
    lesson: 17,
    title: "How to Write a Business Budget Plan",
    duration: "8:07",
    youtubeUrl: "https://www.youtube.com/embed/CnOucbYNsys",
    description: "Create a practical budget that accounts for revenue, expenses, reserves, and growth.",
    objectives: ["Estimate revenue.", "Categorize expenses.", "Plan reserves.", "Monitor variance."],
    keyPoints: ["Revenue assumptions.", "Fixed costs.", "Variable costs.", "Cash reserve.", "Budget review."],
    actionStep: "Create a 12-month business budget.",
    quiz: placeholderQuiz("Business Budget Plan"),
    flashcards: placeholderFlashcards("Business Budget Plan"),
  },
  {
    id: "international-business",
    module: 4,
    lesson: 18,
    title: "International Business Management Basics",
    duration: "3:07",
    youtubeUrl: "https://www.youtube.com/embed/YlUDw2Z09nQ",
    description: "Understand the added considerations involved in operating across borders.",
    objectives: ["Identify international risks.", "Review market differences.", "Consider logistics and compliance."],
    keyPoints: ["Currency.", "Culture.", "Regulation.", "Logistics.", "Tax.", "Market entry."],
    actionStep: "Create a basic international-market research checklist.",
    quiz: placeholderQuiz("International Business"),
    flashcards: placeholderFlashcards("International Business"),
  },
  {
    id: "business-growth",
    module: 5,
    lesson: 19,
    title: "How to Start and Grow Your Business",
    duration: "2:20",
    youtubeUrl: "https://www.youtube.com/embed/BHL_zqoF--8",
    description: "Move from a validated offer to repeatable acquisition, delivery, and growth.",
    objectives: ["Validate an offer.", "Create repeatable systems.", "Measure growth."],
    keyPoints: ["Validation.", "Acquisition.", "Delivery.", "Retention.", "Systems.", "Scale."],
    actionStep: "Choose one growth constraint to solve this month.",
    quiz: placeholderQuiz("Business Growth"),
    flashcards: placeholderFlashcards("Business Growth"),
  },
  {
    id: "increase-profit",
    module: 5,
    lesson: 20,
    title: "How to Make More Money in Your Small Business",
    duration: "2:19",
    youtubeUrl: "https://www.youtube.com/embed/-bO6ktwZlTk",
    description: "Improve revenue and profit through pricing, sales, retention, efficiency, and value.",
    objectives: ["Identify revenue levers.", "Improve margins.", "Strengthen differentiation."],
    keyPoints: ["Pricing.", "Volume.", "Retention.", "Upsells.", "Efficiency.", "Positioning."],
    actionStep: "Choose one revenue lever and one cost-efficiency lever to test.",
    quiz: placeholderQuiz("Increasing Business Profit"),
    flashcards: placeholderFlashcards("Increasing Business Profit"),
  },
  {
    id: "course-introduction",
    module: 1,
    lesson: 21,
    title: "Introducing the Business Management Course",
    duration: "0:58",
    youtubeUrl: "https://www.youtube.com/embed/HE9JioDuXkQ",
    description: "Review the scope and learning goals of the full program.",
    objectives: ["Understand the curriculum.", "Set learning goals.", "Prepare a study routine."],
    keyPoints: ["Finance.", "Strategy.", "Marketing.", "Operations.", "Leadership.", "Growth."],
    actionStep: "Write your top three goals for completing this course.",
    quiz: placeholderQuiz("Course Introduction"),
    flashcards: placeholderFlashcards("Course Introduction"),
  },
  {
    id: "get-customers",
    module: 5,
    lesson: 22,
    title: "How to Get Customers for Your New Business",
    duration: "2:44",
    youtubeUrl: "https://www.youtube.com/embed/rVEvsLNRAuk",
    description: "Build a customer-acquisition process based on targeting, outreach, content, and referrals.",
    objectives: ["Define an ideal customer.", "Select acquisition channels.", "Create an outreach plan."],
    keyPoints: ["Targeting.", "Offer.", "Outreach.", "Content.", "Advertising.", "Referrals."],
    actionStep: "Create a seven-day customer-acquisition sprint.",
    quiz: placeholderQuiz("Customer Acquisition"),
    flashcards: placeholderFlashcards("Customer Acquisition"),
  },
  {
    id: "product-launch",
    module: 6,
    lesson: 23,
    title: "How to Launch a Product Step by Step",
    duration: "3:15",
    youtubeUrl: "https://www.youtube.com/embed/mRYp0_QoW-w",
    description: "Plan a structured product launch from validation through promotion and optimization.",
    objectives: ["Validate demand.", "Prepare positioning.", "Plan launch activity.", "Review results."],
    keyPoints: ["Research.", "Offer.", "Audience.", "Assets.", "Promotion.", "Launch.", "Optimization."],
    actionStep: "Draft a seven-step launch timeline for one offer.",
    quiz: placeholderQuiz("Product Launch"),
    flashcards: placeholderFlashcards("Product Launch"),
  },
  {
    id: "business-leadership",
    module: 6,
    lesson: 24,
    title: "How to Manage a Business and Become a Great Leader",
    duration: "4:27",
    youtubeUrl: "https://www.youtube.com/embed/r1wramwGjmE",
    description: "Develop the communication, judgment, accountability, and vision required for leadership.",
    objectives: ["Define leadership standards.", "Improve communication.", "Build accountability."],
    keyPoints: ["Vision.", "Integrity.", "Communication.", "Delegation.", "Decision-making.", "Accountability."],
    actionStep: "Write your personal leadership code.",
    quiz: placeholderQuiz("Business Leadership"),
    flashcards: placeholderFlashcards("Business Leadership"),
  },
  {
    id: "evaluate-business-ideas",
    module: 7,
    lesson: 25,
    title: "How to Get and Evaluate Business Ideas",
    duration: "30:00",
    youtubeUrl: "https://www.youtube.com/embed/Th8JoIan4dg",
    description:
      "Use Y Combinator's practical framework to notice real problems, compare opportunities, and avoid choosing an idea only because it sounds impressive.",
    objectives: [
      "Recognize the qualities of a promising business problem.",
      "Compare founder fit, urgency, and market evidence.",
      "Choose one idea to validate with customers.",
    ],
    keyPoints: [
      "Strong ideas often begin with a problem the founder understands firsthand.",
      "A painful and frequent problem is usually easier to validate than a vague aspiration.",
      "Founder insight matters, but it still needs evidence from the market.",
      "Start narrow enough to learn quickly.",
    ],
    actionStep:
      "Score three possible business ideas from one to five for urgency, frequency, customer access, founder fit, and willingness to pay.",
    quiz: placeholderQuiz("Evaluating Business Ideas"),
    flashcards: placeholderFlashcards("Evaluating Business Ideas"),
  },
  {
    id: "customer-interviews",
    module: 7,
    lesson: 26,
    title: "How to Talk to Customers",
    duration: "20:00",
    youtubeUrl: "https://www.youtube.com/embed/z1iF1c8w5Lg",
    description:
      "Learn how to run useful customer conversations without pitching, leading the witness, or collecting compliments instead of evidence.",
    objectives: [
      "Prepare neutral customer-interview questions.",
      "Listen for specific past behavior rather than hypothetical intent.",
      "Turn interview patterns into product and service decisions.",
    ],
    keyPoints: [
      "Ask about a real recent experience.",
      "Let the customer do most of the talking.",
      "Avoid explaining or defending the solution during discovery.",
      "Look for repeated patterns across several conversations.",
    ],
    actionStep:
      "Schedule five customer interviews and use the same six neutral questions in each conversation.",
    quiz: placeholderQuiz("Customer Interviews"),
    flashcards: placeholderFlashcards("Customer Interviews"),
  },
  {
    id: "first-customers",
    module: 7,
    lesson: 27,
    title: "How to Get Your First Customers",
    duration: "28:00",
    youtubeUrl: "https://www.youtube.com/embed/hyYCn_kAngI",
    description:
      "Build an early customer-acquisition plan based on direct outreach, focused learning, and hands-on service before attempting to scale.",
    objectives: [
      "Select a reachable early customer segment.",
      "Write a direct outreach message.",
      "Create a learning loop from outreach to delivery.",
    ],
    keyPoints: [
      "Early acquisition is often manual.",
      "Narrow targeting makes outreach more relevant.",
      "The goal is learning and proof, not premature automation.",
      "Founder involvement reveals objections and unmet needs.",
    ],
    actionStep:
      "Build a list of 25 qualified prospects and contact the first five with a short, specific message.",
    quiz: placeholderQuiz("First Customers"),
    flashcards: placeholderFlashcards("First Customers"),
  },
  {
    id: "digital-marketing-plan",
    module: 8,
    lesson: 28,
    title: "Create a Digital Marketing Plan",
    duration: "56:00",
    youtubeUrl: "https://www.youtube.com/embed/4z5X3AGfDfM",
    description:
      "Follow a Grow with Google workshop to connect business goals, audience, channels, content, and measurement in one practical plan.",
    objectives: [
      "Connect marketing activity to a business objective.",
      "Choose channels based on audience behavior.",
      "Define simple measures for awareness, leads, and sales.",
    ],
    keyPoints: [
      "Begin with one measurable business goal.",
      "Describe the audience before choosing a channel.",
      "Match content to the customer's decision stage.",
      "Review results and improve the plan regularly.",
    ],
    actionStep:
      "Create a 30-day digital marketing plan with one goal, one audience, two channels, four content themes, and three measures.",
    quiz: placeholderQuiz("Digital Marketing Plan"),
    flashcards: placeholderFlashcards("Digital Marketing Plan"),
  },
  {
    id: "social-media-foundations",
    module: 8,
    lesson: 29,
    title: "Start Marketing on Social Media",
    duration: "12:00",
    youtubeUrl: "https://www.youtube.com/embed/l3_HA0lBPu0",
    description:
      "Use HubSpot's beginner-friendly approach to choose a focused social channel, publish consistently, and connect content to business outcomes.",
    objectives: [
      "Choose a primary social platform.",
      "Create repeatable content categories.",
      "Connect social activity to a clear call to action.",
    ],
    keyPoints: [
      "Be where the ideal customer already spends time.",
      "Consistency matters more than posting everywhere.",
      "Useful content earns attention and trust.",
      "Track conversations, leads, and conversions—not vanity metrics alone.",
    ],
    actionStep:
      "Choose one primary platform and draft a two-week calendar using three repeatable content categories.",
    quiz: placeholderQuiz("Social Media Foundations"),
    flashcards: placeholderFlashcards("Social Media Foundations"),
  },
  {
    id: "content-marketing-plan",
    module: 8,
    lesson: 30,
    title: "Build a Content Marketing Plan",
    duration: "15:00",
    youtubeUrl: "https://www.youtube.com/embed/cwnwMO6WOCM",
    description:
      "Map useful content to the questions customers ask before, during, and after a purchase.",
    objectives: [
      "Identify customer questions across the buying journey.",
      "Choose content formats that fit the business.",
      "Create a simple publishing and repurposing workflow.",
    ],
    keyPoints: [
      "Content should help a specific audience solve a specific problem.",
      "Different questions appear at awareness, consideration, and decision stages.",
      "One strong idea can become several useful pieces of content.",
      "A publishing system protects consistency.",
    ],
    actionStep:
      "List ten customer questions, group them by buying stage, and turn the strongest three into content briefs.",
    quiz: placeholderQuiz("Content Marketing Plan"),
    flashcards: placeholderFlashcards("Content Marketing Plan"),
  },
  {
    id: "lead-with-purpose",
    module: 9,
    lesson: 31,
    title: "Lead With a Clear Why",
    duration: "18:35",
    youtubeUrl: "https://www.youtube.com/embed/qp0HIF3SfI4",
    description:
      "Study Simon Sinek's framework for communicating purpose so customers and team members understand what the organization stands for.",
    objectives: [
      "Distinguish purpose from products and tactics.",
      "Write a clear purpose statement.",
      "Connect purpose to everyday communication and decisions.",
    ],
    keyPoints: [
      "People respond to meaning as well as features.",
      "Purpose should guide behavior, not remain a slogan.",
      "Clear communication begins from the inside out.",
      "Trust grows when words and actions remain aligned.",
    ],
    actionStep:
      "Write one sentence each for why your business exists, how it serves, and what it offers.",
    quiz: placeholderQuiz("Purposeful Leadership"),
    flashcards: placeholderFlashcards("Purposeful Leadership"),
  },
  {
    id: "giving-useful-feedback",
    module: 9,
    lesson: 32,
    title: "Give Feedback When It Feels Difficult",
    duration: "6:00",
    youtubeUrl: "https://www.youtube.com/embed/jhtwqK3iOV8",
    description:
      "Use a direct, respectful feedback structure to address behavior, explain impact, and agree on a constructive next step.",
    objectives: [
      "Prepare for a difficult feedback conversation.",
      "Separate observed behavior from assumptions.",
      "Agree on a specific improvement and follow-up.",
    ],
    keyPoints: [
      "Give feedback close to the event.",
      "Describe observable behavior and its impact.",
      "Invite the other person's perspective.",
      "End with a clear request and follow-up.",
    ],
    actionStep:
      "Prepare one feedback conversation using four notes: observed behavior, impact, question, and requested next step.",
    quiz: placeholderQuiz("Giving Useful Feedback"),
    flashcards: placeholderFlashcards("Giving Useful Feedback"),
  },
];
