export type ModuleQuizQuestion = {
  id: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
};

export type ModuleQuiz = {
  module: number;
  title: string;
  description: string;
  passingScore: number;
  questions: ModuleQuizQuestion[];
};

export const moduleQuizzes: ModuleQuiz[] = [
  {
    module: 1,
    title: "Business Foundations",
    description:
      "Finance, strategy, self-management, business mistakes, and course foundations.",
    passingScore: 80,
    questions: [
      {
        id: "m1q1",
        question: "What is business revenue?",
        options: [
          "Income generated before expenses",
          "Money remaining after expenses",
          "Only cash invested by the owner",
          "The value of business debt",
        ],
        correctAnswer: 0,
        explanation:
          "Revenue is the income generated by the business before expenses are deducted.",
      },
      {
        id: "m1q2",
        question: "What is profit?",
        options: [
          "Revenue plus liabilities",
          "Money remaining after expenses",
          "All money held in a bank account",
          "The total amount of inventory",
        ],
        correctAnswer: 1,
        explanation:
          "Profit is generally what remains after relevant expenses are deducted from revenue.",
      },
      {
        id: "m1q3",
        question: "Why can a profitable business still experience financial trouble?",
        options: [
          "It may have poor cash flow",
          "Profit automatically creates debt",
          "Revenue cannot be deposited",
          "Expenses never affect cash",
        ],
        correctAnswer: 0,
        explanation:
          "A business may report profit but lack enough available cash to meet immediate obligations.",
      },
      {
        id: "m1q4",
        question: "Which is normally a fixed business expense?",
        options: [
          "Monthly rent",
          "Sales commission",
          "Packaging per order",
          "Transaction fees",
        ],
        correctAnswer: 0,
        explanation:
          "Fixed expenses generally remain relatively stable regardless of sales volume.",
      },
      {
        id: "m1q5",
        question: "What should a business strategy connect?",
        options: [
          "Goals, resources, actions, and measurement",
          "Only a logo and company name",
          "Personal spending and business spending",
          "Products without customers",
        ],
        correctAnswer: 0,
        explanation:
          "A useful strategy connects the business direction to resources, execution, and measurable results.",
      },
      {
        id: "m1q6",
        question: "What should happen before selecting major strategic actions?",
        options: [
          "Clarify the vision and current position",
          "Hire employees immediately",
          "Purchase expensive equipment",
          "Ignore competitors",
        ],
        correctAnswer: 0,
        explanation:
          "Strategy begins with understanding where the business is and where it intends to go.",
      },
      {
        id: "m1q7",
        question: "Which goal is most useful?",
        options: [
          "Increase qualified leads by 20% in 90 days",
          "Become better someday",
          "Make unlimited money",
          "Post more when possible",
        ],
        correctAnswer: 0,
        explanation:
          "Strong goals are specific, measurable, time-bound, and connected to business outcomes.",
      },
      {
        id: "m1q8",
        question: "What is opportunity cost?",
        options: [
          "The value of the best alternative given up",
          "A required business tax",
          "A marketing discount",
          "A bookkeeping category",
        ],
        correctAnswer: 0,
        explanation:
          "Choosing one path usually means giving up another possible use of time, money, or resources.",
      },
      {
        id: "m1q9",
        question: "What is one purpose of a budget?",
        options: [
          "Plan how money will be earned and allocated",
          "Guarantee profit",
          "Remove the need for bookkeeping",
          "Replace customer research",
        ],
        correctAnswer: 0,
        explanation:
          "A budget is a financial plan for expected income, expenses, reserves, and priorities.",
      },
      {
        id: "m1q10",
        question: "Which habit supports effective founder self-management?",
        options: [
          "Time-blocking priorities",
          "Responding to every distraction",
          "Avoiding delegation",
          "Changing goals daily",
        ],
        correctAnswer: 0,
        explanation:
          "Time-blocking helps protect focused work and important leadership responsibilities.",
      },
      {
        id: "m1q11",
        question: "Why should personal and business finances be separated?",
        options: [
          "To improve records, clarity, and accountability",
          "To make expenses harder to track",
          "To avoid creating financial reports",
          "To eliminate all tax obligations",
        ],
        correctAnswer: 0,
        explanation:
          "Separating finances produces cleaner records and makes business performance easier to evaluate.",
      },
      {
        id: "m1q12",
        question: "Which is a common management mistake?",
        options: [
          "Making decisions without tracking results",
          "Reviewing performance regularly",
          "Documenting processes",
          "Listening to customers",
        ],
        correctAnswer: 0,
        explanation:
          "Without measurement, the owner cannot reliably know what is working or failing.",
      },
      {
        id: "m1q13",
        question: "What is the purpose of a financial snapshot?",
        options: [
          "Summarize revenue, expenses, cash, debt, and profit",
          "Replace all accounting records",
          "Design advertising graphics",
          "Create employee schedules",
        ],
        correctAnswer: 0,
        explanation:
          "A financial snapshot provides a quick view of the business's current financial condition.",
      },
      {
        id: "m1q14",
        question: "What should a founder do when a strategy is not producing results?",
        options: [
          "Review the data and adjust the plan",
          "Continue indefinitely without changes",
          "Stop measuring performance",
          "Increase spending without analysis",
        ],
        correctAnswer: 0,
        explanation:
          "Strategy requires review and adjustment based on measurable performance.",
      },
      {
        id: "m1q15",
        question: "What is the strongest foundation for business decisions?",
        options: [
          "Accurate information and clear objectives",
          "Assumptions only",
          "Competitor imitation only",
          "Emotional reactions",
        ],
        correctAnswer: 0,
        explanation:
          "Clear objectives supported by reliable information lead to stronger decisions.",
      },
    ],
  },

  {
    module: 2,
    title: "Marketing & Operations",
    description:
      "Marketing channels, operating systems, quality management, and repeatable delivery.",
    passingScore: 80,
    questions: [
      {
        id: "m2q1",
        question: "What should come before choosing a marketing channel?",
        options: [
          "Understanding the target customer",
          "Buying every available advertisement",
          "Copying a competitor's slogan",
          "Increasing prices immediately",
        ],
        correctAnswer: 0,
        explanation:
          "Marketing is more effective when the audience, problem, and desired outcome are understood first.",
      },
      {
        id: "m2q2",
        question: "What is a marketing channel?",
        options: [
          "A method used to reach and communicate with customers",
          "A business bank account",
          "An employee handbook",
          "A financial statement",
        ],
        correctAnswer: 0,
        explanation:
          "Channels include methods such as email, social media, referrals, advertising, and events.",
      },
      {
        id: "m2q3",
        question: "Which metric helps measure customer acquisition efficiency?",
        options: [
          "Customer acquisition cost",
          "Office square footage",
          "Number of internal meetings",
          "Employee dress code",
        ],
        correctAnswer: 0,
        explanation:
          "Customer acquisition cost measures how much is spent to gain a new customer.",
      },
      {
        id: "m2q4",
        question: "Why should businesses test multiple marketing methods?",
        options: [
          "To learn which channels produce the best results",
          "To avoid measuring anything",
          "To guarantee every campaign succeeds",
          "To eliminate the need for an offer",
        ],
        correctAnswer: 0,
        explanation:
          "Testing helps identify which channels, messages, and audiences create the strongest return.",
      },
      {
        id: "m2q5",
        question: "What is the purpose of business operations?",
        options: [
          "Turn inputs into consistent customer outcomes",
          "Create random activity",
          "Focus only on company branding",
          "Replace financial management",
        ],
        correctAnswer: 0,
        explanation:
          "Operations organize people, processes, tools, and resources to deliver products or services.",
      },
      {
        id: "m2q6",
        question: "What is a standard operating procedure?",
        options: [
          "A documented method for completing a recurring process",
          "A list of customer complaints",
          "A personal calendar",
          "An advertising budget only",
        ],
        correctAnswer: 0,
        explanation:
          "An SOP documents how a repeatable task should be performed.",
      },
      {
        id: "m2q7",
        question: "What does a process bottleneck do?",
        options: [
          "Restricts the speed or capacity of a workflow",
          "Automatically improves quality",
          "Eliminates customer demand",
          "Increases every employee's productivity",
        ],
        correctAnswer: 0,
        explanation:
          "A bottleneck is the step that limits the performance of the overall process.",
      },
      {
        id: "m2q8",
        question: "Why map the customer journey?",
        options: [
          "To understand each step from awareness through delivery and retention",
          "To replace customer support",
          "To avoid documenting operations",
          "To calculate payroll",
        ],
        correctAnswer: 0,
        explanation:
          "Journey mapping reveals the customer's experience and identifies opportunities for improvement.",
      },
      {
        id: "m2q9",
        question: "What is quality management designed to improve?",
        options: [
          "Consistency, reliability, and customer outcomes",
          "Only the company logo",
          "Only employee attendance",
          "The number of meetings",
        ],
        correctAnswer: 0,
        explanation:
          "Quality management creates standards and systems that improve delivery and reduce errors.",
      },
      {
        id: "m2q10",
        question: "What should happen after a quality problem is discovered?",
        options: [
          "Identify the cause and implement corrective action",
          "Hide the problem",
          "Blame the customer automatically",
          "Stop tracking quality",
        ],
        correctAnswer: 0,
        explanation:
          "Corrective action addresses the cause of the problem and helps prevent it from happening again.",
      },
      {
        id: "m2q11",
        question: "Which is an example of a quality standard?",
        options: [
          "All customer inquiries receive a response within one business day",
          "Employees respond whenever convenient",
          "Products are checked only after complaints",
          "No service outcome is measured",
        ],
        correctAnswer: 0,
        explanation:
          "A quality standard should define a specific, measurable expectation.",
      },
      {
        id: "m2q12",
        question: "What is continuous improvement?",
        options: [
          "Regularly making measured process improvements",
          "Changing every process daily",
          "Avoiding customer feedback",
          "Ignoring small errors",
        ],
        correctAnswer: 0,
        explanation:
          "Continuous improvement involves ongoing, evidence-based refinements to products and processes.",
      },
      {
        id: "m2q13",
        question: "What makes an operating system scalable?",
        options: [
          "Documented processes that can be repeated by others",
          "All knowledge remaining in the founder's head",
          "Every customer receiving a completely random process",
          "No defined responsibilities",
        ],
        correctAnswer: 0,
        explanation:
          "Documented, repeatable processes allow the business to grow without depending entirely on one person.",
      },
      {
        id: "m2q14",
        question: "Why assign responsibility for each operational step?",
        options: [
          "To establish ownership and accountability",
          "To create confusion",
          "To eliminate documentation",
          "To avoid measuring deadlines",
        ],
        correctAnswer: 0,
        explanation:
          "Clear ownership prevents tasks from being overlooked and improves accountability.",
      },
      {
        id: "m2q15",
        question: "Which combination best supports operational improvement?",
        options: [
          "Standards, measurement, feedback, and correction",
          "Assumptions, silence, and inconsistency",
          "More meetings without data",
          "Constant changes without review",
        ],
        correctAnswer: 0,
        explanation:
          "Strong operations improve through defined standards, performance data, feedback, and corrective action.",
      },
    ],
  },

  {
    module: 3,
    title: "People, Research & Administration",
    description:
      "Human resources, business research, management skills, documents, and administration.",
    passingScore: 80,
    questions: [
      {
        id: "m3q1",
        question: "What is a primary responsibility of human resource management?",
        options: [
          "Recruiting, developing, and supporting employees",
          "Designing every marketing advertisement",
          "Managing only inventory",
          "Setting customer prices only",
        ],
        correctAnswer: 0,
        explanation:
          "HR supports recruiting, onboarding, training, performance, policies, and workplace culture.",
      },
      {
        id: "m3q2",
        question: "Why is a clear job description important?",
        options: [
          "It defines responsibilities, qualifications, and expectations",
          "It guarantees every hire succeeds",
          "It replaces employee training",
          "It eliminates the need for management",
        ],
        correctAnswer: 0,
        explanation:
          "A clear job description helps attract suitable candidates and establishes role expectations.",
      },
      {
        id: "m3q3",
        question: "What is onboarding?",
        options: [
          "The process of integrating and preparing a new employee",
          "The process of firing every employee",
          "A customer acquisition campaign",
          "A financial audit",
        ],
        correctAnswer: 0,
        explanation:
          "Onboarding introduces the employee to the organization, role, systems, expectations, and culture.",
      },
      {
        id: "m3q4",
        question: "What should performance management include?",
        options: [
          "Expectations, feedback, measurement, and development",
          "Only criticism",
          "No documented goals",
          "Compensation only",
        ],
        correctAnswer: 0,
        explanation:
          "Performance management aligns goals, measures outcomes, provides feedback, and supports development.",
      },
      {
        id: "m3q5",
        question: "What is primary research?",
        options: [
          "Information collected directly from customers or the market",
          "Information copied from competitors only",
          "Old accounting records",
          "Internal employee schedules",
        ],
        correctAnswer: 0,
        explanation:
          "Primary research includes surveys, interviews, observations, and original experiments.",
      },
      {
        id: "m3q6",
        question: "What is secondary research?",
        options: [
          "Analysis of existing reports, studies, and published information",
          "Only speaking with one customer",
          "Creating payroll reports",
          "Writing employee policies",
        ],
        correctAnswer: 0,
        explanation:
          "Secondary research uses information that has already been collected and published.",
      },
      {
        id: "m3q7",
        question: "What is the best reason to interview potential customers?",
        options: [
          "Understand their problems, priorities, and buying behavior",
          "Convince them every idea is perfect",
          "Avoid testing assumptions",
          "Replace all market data",
        ],
        correctAnswer: 0,
        explanation:
          "Customer interviews help validate problems and reveal how customers think and make decisions.",
      },
      {
        id: "m3q8",
        question: "Which management skill improves clarity across a team?",
        options: [
          "Communication",
          "Avoidance",
          "Guessing",
          "Silence",
        ],
        correctAnswer: 0,
        explanation:
          "Clear communication aligns expectations, responsibilities, decisions, and timelines.",
      },
      {
        id: "m3q9",
        question: "Why is delegation important?",
        options: [
          "It distributes responsibility and increases capacity",
          "It removes all accountability",
          "It prevents employee development",
          "It requires the founder to perform every task",
        ],
        correctAnswer: 0,
        explanation:
          "Delegation allows work to be assigned appropriately while helping others develop skills.",
      },
      {
        id: "m3q10",
        question: "Which document commonly defines an agreement between parties?",
        options: [
          "Contract",
          "Logo file",
          "Social-media caption",
          "Personal journal",
        ],
        correctAnswer: 0,
        explanation:
          "A contract documents the agreed obligations, rights, and terms between parties.",
      },
      {
        id: "m3q11",
        question: "Why should business documents be organized securely?",
        options: [
          "To protect information and make records accessible when needed",
          "To make records impossible to find",
          "To avoid compliance requirements",
          "To prevent financial review",
        ],
        correctAnswer: 0,
        explanation:
          "Secure organization protects sensitive information and supports efficient operations.",
      },
      {
        id: "m3q12",
        question: "What does business administration coordinate?",
        options: [
          "Records, schedules, communication, policies, and workflows",
          "Only advertising",
          "Only product design",
          "Only customer reviews",
        ],
        correctAnswer: 0,
        explanation:
          "Administration organizes the recurring internal functions that keep the business operating.",
      },
      {
        id: "m3q13",
        question: "What is the purpose of an administrative calendar?",
        options: [
          "Track recurring deadlines, filings, meetings, and tasks",
          "Replace all company policies",
          "Create customer demand",
          "Calculate profit automatically",
        ],
        correctAnswer: 0,
        explanation:
          "An administrative calendar helps prevent important recurring responsibilities from being missed.",
      },
      {
        id: "m3q14",
        question: "What should happen when research contradicts the founder's assumption?",
        options: [
          "Reevaluate the idea using the evidence",
          "Ignore the evidence automatically",
          "Stop all research",
          "Increase spending immediately",
        ],
        correctAnswer: 0,
        explanation:
          "Research is valuable because it helps challenge assumptions before larger investments are made.",
      },
      {
        id: "m3q15",
        question: "Which combination supports effective people management?",
        options: [
          "Clear roles, training, feedback, and accountability",
          "Confusion, silence, and inconsistent expectations",
          "No onboarding or standards",
          "Hiring without role definitions",
        ],
        correctAnswer: 0,
        explanation:
          "Employees perform better when expectations, training, communication, and accountability are clear.",
      },
    ],
  },

  {
    module: 4,
    title: "Accounting, Economics & Planning",
    description:
      "Accounting, demand and supply, economics, budgeting, and international business.",
    passingScore: 80,
    questions: [
      {
        id: "m4q1",
        question: "What is bookkeeping?",
        options: [
          "Recording and organizing business transactions",
          "Creating social-media graphics",
          "Hiring employees",
          "Designing products",
        ],
        correctAnswer: 0,
        explanation:
          "Bookkeeping records the financial transactions used to produce reliable business reports.",
      },
      {
        id: "m4q2",
        question: "What does an income statement show?",
        options: [
          "Revenue, expenses, and profit over a period",
          "Only cash in the bank",
          "Only company assets",
          "Employee schedules",
        ],
        correctAnswer: 0,
        explanation:
          "The income statement summarizes financial performance over a defined period.",
      },
      {
        id: "m4q3",
        question: "What does a balance sheet show?",
        options: [
          "Assets, liabilities, and equity at a point in time",
          "Only monthly sales",
          "Only advertising costs",
          "Future customer demand",
        ],
        correctAnswer: 0,
        explanation:
          "A balance sheet presents what the business owns, owes, and the residual equity.",
      },
      {
        id: "m4q4",
        question: "Why reconcile a bank account?",
        options: [
          "To compare internal records with bank activity",
          "To increase demand automatically",
          "To avoid recording expenses",
          "To replace financial statements",
        ],
        correctAnswer: 0,
        explanation:
          "Reconciliation identifies missing, duplicated, incorrect, or unauthorized transactions.",
      },
      {
        id: "m4q5",
        question: "What is demand?",
        options: [
          "The quantity customers are willing and able to purchase",
          "The quantity businesses refuse to sell",
          "A company's liabilities",
          "An employee benefit",
        ],
        correctAnswer: 0,
        explanation:
          "Demand reflects customer willingness and ability to purchase at different prices.",
      },
      {
        id: "m4q6",
        question: "What is supply?",
        options: [
          "The quantity producers are willing and able to offer",
          "The number of customer complaints",
          "The amount of company debt",
          "A leadership method",
        ],
        correctAnswer: 0,
        explanation:
          "Supply describes how much producers make available at different prices.",
      },
      {
        id: "m4q7",
        question: "When demand rises while supply remains limited, what commonly happens?",
        options: [
          "Price pressure may increase",
          "All costs disappear",
          "Demand automatically becomes zero",
          "Accounting is no longer needed",
        ],
        correctAnswer: 0,
        explanation:
          "Higher demand relative to limited supply often places upward pressure on prices.",
      },
      {
        id: "m4q8",
        question: "What is scarcity?",
        options: [
          "Limited resources relative to competing wants",
          "Unlimited money and time",
          "A customer service policy",
          "A type of business contract",
        ],
        correctAnswer: 0,
        explanation:
          "Scarcity requires individuals and businesses to choose how limited resources should be used.",
      },
      {
        id: "m4q9",
        question: "What should a budget variance analysis compare?",
        options: [
          "Planned results with actual results",
          "Two company logos",
          "Employee titles only",
          "Customer names",
        ],
        correctAnswer: 0,
        explanation:
          "Variance analysis shows where actual revenue or spending differs from the budget.",
      },
      {
        id: "m4q10",
        question: "Why should a business maintain a cash reserve?",
        options: [
          "To help manage unexpected costs and timing gaps",
          "To avoid all financial planning",
          "To guarantee unlimited growth",
          "To eliminate bookkeeping",
        ],
        correctAnswer: 0,
        explanation:
          "A cash reserve can protect the company during emergencies, downturns, or delayed payments.",
      },
      {
        id: "m4q11",
        question: "What is a variable expense?",
        options: [
          "A cost that changes with sales or activity",
          "A cost that never changes",
          "A business asset",
          "Owner equity",
        ],
        correctAnswer: 0,
        explanation:
          "Variable costs change as production, sales, or operational activity changes.",
      },
      {
        id: "m4q12",
        question: "Which factor should be considered in international business?",
        options: [
          "Currency, culture, law, tax, and logistics",
          "Only the company logo",
          "Only local employee schedules",
          "Only domestic advertising",
        ],
        correctAnswer: 0,
        explanation:
          "Cross-border activity adds currency, regulatory, cultural, tax, and logistics considerations.",
      },
      {
        id: "m4q13",
        question: "What is currency risk?",
        options: [
          "The possibility that exchange-rate changes affect value",
          "The risk of hiring an employee",
          "A customer-service problem",
          "A social-media risk only",
        ],
        correctAnswer: 0,
        explanation:
          "Exchange-rate movements can change revenue, costs, pricing, and profit across countries.",
      },
      {
        id: "m4q14",
        question: "Why analyze the economic environment?",
        options: [
          "To understand factors affecting customers, costs, competition, and growth",
          "To avoid planning",
          "To replace internal records",
          "To eliminate business risk",
        ],
        correctAnswer: 0,
        explanation:
          "Economic conditions influence demand, financing, pricing, wages, and customer behavior.",
      },
      {
        id: "m4q15",
        question: "Which sequence supports sound financial planning?",
        options: [
          "Estimate, budget, track, compare, and adjust",
          "Spend, ignore, and guess",
          "Borrow without reviewing",
          "Set no targets",
        ],
        correctAnswer: 0,
        explanation:
          "Financial planning works best when estimates are tracked against actual performance and adjusted.",
      },
    ],
  },

  {
    module: 5,
    title: "Growth & Customer Acquisition",
    description:
      "Customer service, growth systems, revenue improvement, and customer acquisition.",
    passingScore: 80,
    questions: [
      {
        id: "m5q1",
        question: "What is the foundation of strong customer service?",
        options: [
          "Understanding and resolving the customer's need",
          "Responding as slowly as possible",
          "Avoiding responsibility",
          "Using unclear communication",
        ],
        correctAnswer: 0,
        explanation:
          "Strong service begins with listening, understanding, communication, and useful resolution.",
      },
      {
        id: "m5q2",
        question: "Why should a business define response-time standards?",
        options: [
          "To create consistent customer expectations",
          "To avoid answering customers",
          "To increase confusion",
          "To remove accountability",
        ],
        correctAnswer: 0,
        explanation:
          "Response standards help the team deliver a consistent level of service.",
      },
      {
        id: "m5q3",
        question: "What should happen after resolving a customer problem?",
        options: [
          "Follow up and confirm the resolution",
          "Delete all records",
          "Ignore the customer",
          "End all communication immediately",
        ],
        correctAnswer: 0,
        explanation:
          "Follow-up confirms satisfaction and demonstrates responsibility.",
      },
      {
        id: "m5q4",
        question: "What is customer retention?",
        options: [
          "Keeping customers engaged and purchasing over time",
          "Only gaining first-time buyers",
          "Reducing product quality",
          "Avoiding customer communication",
        ],
        correctAnswer: 0,
        explanation:
          "Retention measures the business's ability to maintain customer relationships.",
      },
      {
        id: "m5q5",
        question: "Why are repeat customers valuable?",
        options: [
          "They can increase lifetime value and reduce acquisition pressure",
          "They always require more advertising than new customers",
          "They eliminate the need for quality",
          "They never provide referrals",
        ],
        correctAnswer: 0,
        explanation:
          "Repeat customers may purchase more, refer others, and cost less to retain than acquiring new customers.",
      },
      {
        id: "m5q6",
        question: "What should a growth strategy identify first?",
        options: [
          "The main constraint limiting performance",
          "A new logo",
          "More meetings",
          "More products without research",
        ],
        correctAnswer: 0,
        explanation:
          "Solving the most important constraint can produce more meaningful growth than scattered activity.",
      },
      {
        id: "m5q7",
        question: "What is a scalable growth system?",
        options: [
          "A repeatable method for acquiring and serving customers",
          "A process known only by the founder",
          "A random collection of tactics",
          "A plan without measurement",
        ],
        correctAnswer: 0,
        explanation:
          "Scalable systems can be repeated, measured, documented, and improved.",
      },
      {
        id: "m5q8",
        question: "Which is a revenue-growth lever?",
        options: [
          "Increasing conversion, pricing, frequency, or retention",
          "Ignoring existing customers",
          "Removing measurement",
          "Increasing errors",
        ],
        correctAnswer: 0,
        explanation:
          "Revenue can grow through more customers, higher conversion, better pricing, repeat purchases, or retention.",
      },
      {
        id: "m5q9",
        question: "What is an upsell?",
        options: [
          "Offering a customer a higher-value related option",
          "Refusing to serve a customer",
          "Lowering product quality",
          "Deleting a product",
        ],
        correctAnswer: 0,
        explanation:
          "An upsell offers an expanded or higher-value version of the purchase.",
      },
      {
        id: "m5q10",
        question: "What should customer acquisition begin with?",
        options: [
          "A clear ideal-customer profile and offer",
          "Advertising to everyone",
          "No defined problem",
          "No pricing",
        ],
        correctAnswer: 0,
        explanation:
          "Acquisition improves when the business knows who it serves and what value it offers.",
      },
      {
        id: "m5q11",
        question: "What is a conversion rate?",
        options: [
          "The percentage of prospects who take a desired action",
          "The total amount of company debt",
          "The number of employees",
          "The value of fixed assets",
        ],
        correctAnswer: 0,
        explanation:
          "Conversion rate measures how effectively prospects move to the desired action.",
      },
      {
        id: "m5q12",
        question: "Why should acquisition channels be tracked separately?",
        options: [
          "To identify which channels produce effective customers",
          "To make reporting less accurate",
          "To hide marketing costs",
          "To prevent improvement",
        ],
        correctAnswer: 0,
        explanation:
          "Separate tracking allows comparison of cost, volume, quality, and conversion by channel.",
      },
      {
        id: "m5q13",
        question: "What is customer lifetime value?",
        options: [
          "The estimated value a customer creates throughout the relationship",
          "The cost of one advertisement",
          "The price of one employee",
          "The value of inventory only",
        ],
        correctAnswer: 0,
        explanation:
          "Customer lifetime value estimates total economic value across the customer's relationship with the company.",
      },
      {
        id: "m5q14",
        question: "What usually improves referrals?",
        options: [
          "A strong customer experience and a clear referral request",
          "Poor communication",
          "Inconsistent delivery",
          "Unresolved complaints",
        ],
        correctAnswer: 0,
        explanation:
          "Satisfied customers are more likely to refer others, especially when the process is easy.",
      },
      {
        id: "m5q15",
        question: "Which growth approach is strongest?",
        options: [
          "Measure acquisition, delivery, retention, and profitability together",
          "Focus only on follower count",
          "Ignore fulfillment capacity",
          "Grow revenue without reviewing costs",
        ],
        correctAnswer: 0,
        explanation:
          "Sustainable growth requires customer acquisition, operational delivery, retention, and financial health.",
      },
    ],
  },

  {
    module: 6,
    title: "Launch & Leadership",
    description:
      "Product launching, business management, leadership, accountability, and execution.",
    passingScore: 80,
    questions: [
      {
        id: "m6q1",
        question: "What should happen before a full product launch?",
        options: [
          "Validate the problem, audience, and offer",
          "Spend the entire budget",
          "Ignore customer feedback",
          "Hire a large team immediately",
        ],
        correctAnswer: 0,
        explanation:
          "Validation reduces risk by confirming that the audience values the proposed solution.",
      },
      {
        id: "m6q2",
        question: "What is product positioning?",
        options: [
          "How the offer is understood relative to customer needs and alternatives",
          "Where inventory is stored",
          "The company's payroll schedule",
          "An employee benefit",
        ],
        correctAnswer: 0,
        explanation:
          "Positioning defines the place the product should occupy in the customer's mind.",
      },
      {
        id: "m6q3",
        question: "What should a launch timeline include?",
        options: [
          "Preparation, promotion, launch, delivery, and review",
          "Only the launch date",
          "Only product pricing",
          "Only employee names",
        ],
        correctAnswer: 0,
        explanation:
          "A launch timeline coordinates the actions required before, during, and after release.",
      },
      {
        id: "m6q4",
        question: "Why collect feedback during a launch?",
        options: [
          "To improve messaging, delivery, and the offer",
          "To prove every assumption correct",
          "To stop communicating with customers",
          "To eliminate measurement",
        ],
        correctAnswer: 0,
        explanation:
          "Launch feedback reveals objections, confusion, strengths, and areas for improvement.",
      },
      {
        id: "m6q5",
        question: "Which launch metric is important?",
        options: [
          "Conversion rate",
          "Number of internal emails only",
          "Office temperature",
          "Employee commute distance",
        ],
        correctAnswer: 0,
        explanation:
          "Conversion rate helps measure how effectively interest becomes the desired purchase or action.",
      },
      {
        id: "m6q6",
        question: "What is leadership vision?",
        options: [
          "A clear description of the future the leader is working toward",
          "A list of daily complaints",
          "A financial transaction",
          "An employee timesheet",
        ],
        correctAnswer: 0,
        explanation:
          "Vision gives direction and helps align people, priorities, and decisions.",
      },
      {
        id: "m6q7",
        question: "Why is integrity essential to leadership?",
        options: [
          "It builds trust between words, decisions, and actions",
          "It allows leaders to avoid accountability",
          "It removes the need for communication",
          "It guarantees immediate profit",
        ],
        correctAnswer: 0,
        explanation:
          "Integrity creates credibility by aligning stated values with actual conduct.",
      },
      {
        id: "m6q8",
        question: "What is effective delegation?",
        options: [
          "Assigning responsibility with authority, expectations, and follow-up",
          "Giving unclear tasks without support",
          "Avoiding accountability",
          "Doing every task personally",
        ],
        correctAnswer: 0,
        explanation:
          "Effective delegation clearly defines the result, authority, resources, timeline, and accountability.",
      },
      {
        id: "m6q9",
        question: "What is accountability?",
        options: [
          "Taking responsibility for commitments and results",
          "Avoiding difficult conversations",
          "Blaming others automatically",
          "Ignoring deadlines",
        ],
        correctAnswer: 0,
        explanation:
          "Accountability means owning responsibilities, actions, and outcomes.",
      },
      {
        id: "m6q10",
        question: "What should guide a difficult leadership decision?",
        options: [
          "Values, evidence, consequences, and the mission",
          "Impulse alone",
          "Popularity only",
          "Competitor behavior only",
        ],
        correctAnswer: 0,
        explanation:
          "Strong decisions consider principles, facts, stakeholders, risks, and organizational purpose.",
      },
      {
        id: "m6q11",
        question: "What is the purpose of a leadership code?",
        options: [
          "Define the standards and principles that guide behavior",
          "Replace every company policy",
          "Guarantee employee agreement",
          "Eliminate all conflict",
        ],
        correctAnswer: 0,
        explanation:
          "A leadership code clarifies how the leader intends to make decisions and treat others.",
      },
      {
        id: "m6q12",
        question: "How should a leader respond to a failed initiative?",
        options: [
          "Review the evidence, accept responsibility, learn, and adjust",
          "Hide the results",
          "Blame the team without analysis",
          "Repeat the same plan without changes",
        ],
        correctAnswer: 0,
        explanation:
          "Failure becomes useful when leaders examine it honestly and apply the lesson.",
      },
      {
        id: "m6q13",
        question: "What helps a team execute consistently?",
        options: [
          "Clear priorities, owners, deadlines, and follow-up",
          "Changing expectations every day",
          "No defined responsibilities",
          "Avoiding progress reviews",
        ],
        correctAnswer: 0,
        explanation:
          "Execution improves when people understand what must happen, who owns it, and when it is due.",
      },
      {
        id: "m6q14",
        question: "What is servant leadership?",
        options: [
          "Leading by supporting people and the mission, not only personal power",
          "Allowing every standard to disappear",
          "Avoiding difficult decisions",
          "Refusing to hold people accountable",
        ],
        correctAnswer: 0,
        explanation:
          "Servant leadership prioritizes the growth, wellbeing, and contribution of others while maintaining standards.",
      },
      {
        id: "m6q15",
        question: "What defines a successful product launch and leadership process?",
        options: [
          "Preparation, communication, execution, measurement, and improvement",
          "Luck without planning",
          "A large audience without an offer",
          "Activity without outcomes",
        ],
        correctAnswer: 0,
        explanation:
          "Both launches and leadership depend on preparation, aligned execution, measurement, and learning.",
      },
    ],
  },
];